// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const navbarContainer: string;
export const navbarItemContainer: string;
export const navbarItemBox: string;
export const navbarItem: string;
