// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const metaContainer: string;
export const collectionList: string;
export const contentMeta: string;
export const creationMeta: string;
