// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const rotatorItemContainer: string;
export const rotatorContainer: string;
export const rotatorCounterContainer: string;
export const rotatorCounter: string;
export const activeCounter: string;
export const invisible: string;
